### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by findmory** [vasilestefirta/react-native-eslint-prettier-example#1]
This example was super helpful.  The out-of-the-box `react-native init <project>` on M1 Mac has ESLint / Prettier combo not working, which I believe is an issue with `@react-native-community/eslint-config` which comes installed.   I followed your steps but I had to use `eslint-config-prettier@^7` (instead of v8) and same for `eslint@^7`.   

If you want I can do a pull request showing how it works today using those versions.

I'm also going to try and figure out how to get it working with `eslint@^8` but that will take some more time.  I didn't know how else to communicate with you, so feel free to close this issue, but I thought it was a decent way to discuss.  Thanks again.

**Comment by kiranojhanp** [comment]
```json
{
  "env": {
    "es2021": true,
    "node": true
  },
  "extends": ["plugin:react/recommended", "airbnb", "airbnb/hooks", "prettier"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": ["react", "react-native", "@typescript-eslint"],
  "rules": {}
}

```

Replace your .eslintrc.json with this setting and it will work

**Comment by findmory** [comment]
thank you @kiranojhanp but this doesn't solve the problem for me

[Info  - 10:57:39 AM] Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/parser' Require stack: - /Users/mory/repos/xxx/yyy/react-native-app/.eslintrc.json

**Comment by findmory** [comment]
Removed my `node_modules` and `package-lock.json`, put back versions 8 for `eslint` and `eslint-config-prettier` in my `package.json` and setup my `.eslintrc.json` like this (since I'm not using typescript)

```
{
  "env": {
    "es2021": true,
    "node": true
  },
  "extends": ["plugin:react/recommended", "airbnb", "airbnb/hooks", "prettier"],

  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": ["react", "react-native"],
  "rules": {}
}
```

and (importantly) installed packages with yarn (instead of npm) and now I have working lint / prettier with version 8.4.1 of Eslint !

**Comment by vasilestefirta** [comment]
Glad it's all working well now!
